name: PyPiPublish

on:
  push:
  pull_request:

jobs:
  dist:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build sdist and wheel
        run: pipx run build

      - name: Upload sdist and wheel as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist

  pypi:
    # upload to PyPI and make a release on every tag
    if: github.ref_type == 'tag'
    needs: [dist]

    runs-on: ubuntu-latest
    permissions:
      # this permission is mandatory for trusted publishing To PyPI
      id-token: write
    # Specify the GitHub Environment to publish to
    environment: release

    steps:
      # download sdist and wheel from dist job
      - uses: actions/download-artifact@v8
        with:
          path: dist
      # publish to PyPI using trusted publishing
      - name: Publish to PyPI (v1.14.0)
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
